# Basics Python





## Notwendige Bibliotheken

In [4]:
import numpy as np
import pandas as pd
import math           # for factorial

$\color{green}{\textbf{Grüne Schrift}}$: Zuteilung der Aufgaben zu bestimmten Teilnehmern (Usern). Es sind jeweils die Aufgaben bis zum nächsten $\color{green}{\textbf{User}}$ Marker (oder bis zum Ende des Notebooks) zu lösen.

## Grundlagen

$\color{green}{\textbf{User 1}}$: 

$\color{blue}{\text{Aufgabe 1a}}$. Was ist der Unterschied zwischen […] und (…)?. Finden Sie zwei Beispiel-Befehle für die Verwendung von Listen und zwei Beispiel-Befehle für die Verwendung von Tupeln.

---

$\color{blue}{\text{Aufgabe 1b}}$. Mit ``myset= set{[1,4,2,1,1]}`` definiert man ein __Set__. Was sind die Unterschiede zwischen einem Set und einer Liste ``lst= [1,4,2,1,1]``?. Bestimmen Sie programmatisch die Anzahl der Element von ``myset`` und von ``lst``.

---

$\color{green}{\textbf{User 2}}$: 

$\color{blue}{\text{Aufgabe 2a}}$. Erzeugen Sie einen Vektor mit den Zahlen von 1 bis 20. Transformieren Sie diesen Vektor in eine Matrix mit 5 Zeilen und 4 Spalten.

$\color{blue}{\text{Aufgabe 2b}}$. Ermitteln Sie Min und Mittelwert jeder Spalte dieser Matrix.

$\color{blue}{\text{Aufgabe 2c}}$. Transponieren Sie die Matrix und ermitteln Sie Min und Mittelwert erneut.

$\color{blue}{\text{Aufgabe 2d}}$. Wie kann man mit einem einzeiligen Befehl für ein NumPy Array für **jede** Spalte Mittelwert, Standardabweichung, Min und Max ermitteln? 

---

$\color{green}{\textbf{User 3}}$: 

$\color{blue}{\text{Aufgabe 3a}}$. Wie berechnet man in Python $100 \mod 7$? 

$\color{blue}{\text{Aufgabe 3b}}$. Wie ermittelt man in Python den Wahrheitsgehalt der Aussage $x<2 \wedge x>0$? 

Wie lauten die anderen logischen Operatoren (nicht, oder, gleich, ungleich)?

$\color{green}{\textbf{User 4}}$: 

$\color{blue}{\text{Aufgabe 4}}$ 

(a) Erzeugen Sie eine 3x2 Matrix mit [0,1]-gleichverteilten Zufallszahlen.

(b) Erzeugen Sie eine 3x2 Matrix mit standardnormalverteilten Zufallszahlen.

## Python IDEs







$\color{blue}{\text{Aufgabe 5}}$. Vergleichen Sie die Entwicklungsumgebungen Anaconda und Google Colab! Welche Unterschiede, Vor- und Nachteile sehen Sie?

$\color{green}{\textbf{User 5}}$: 

$\color{blue}{\text{Aufgabe 6a}}$. Wie kann man einen (.csv oder .py) File für ein Google Colab Notebook verfügbar machen? 

---

### Concatenator

$\color{blue}{\text{Aufgabe 6b}}$. Seien 
$A=\left(\begin{matrix} 1 & 3 & 5 \\
                        2 & 4 & 6\end{matrix}\right)$ und 
$B=\left(\begin{matrix} 0 &10 &20 \\
                        0 &-4 &-8\end{matrix}\right)$ 
zwei `numpy`-Arrays. Bilden Sie mit *einem* Befehl die Column-Concatenation $\left(\begin{matrix} A&B \end{matrix}\right)$  (eine 2x6 Matrix) und die Row-Concatenation 
$\left(\begin{matrix} A \\B \end{matrix}\right)$  (eine 4x3 Matrix).

$\color{green}{\textbf{User 6}}$: 

## Python-Programmierung


$\color{blue}{\text{Aufgabe 7}}$. Schreiben Sie ein Programm, das für $n,k \in \mathbb{N}_0$ alle Kombinationen $\left(\begin{matrix} n \\ k  \end{matrix}\right) = \frac{n!}{k!(n-k)!}$ berechnen kann und dabei ungültige Eingaben abfängt (wenn möglich, mit Exceptions und ‚try-except‘). Suchen Sie dann nach einem bereits existierenden Python Package, das dasselbe leistet.

---

$\color{green}{\textbf{User 7}}$: 

## Matrix und Vektor Manipulation

$\color{blue}{\text{Aufgabe 8}}$.	Gegeben sei das 3 x 3 `numpy` Array `a`:

In [11]:
a = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Was liefert `a[-1,2]`, `a[-2,2]`, `a[-3,2]` und `a[-4,2]` zurück? Geben Sie die Dimensionen von ``a`` und die 1. Spalte von ``a`` aus.

$\color{blue}{\text{Aufgabe 9}}$.	Sei `v` ein Vektor der Länge 100 und `nd` eine Matrix der Größe 100*100. Wie viele Elemente liefert `v[10:20]`, `nd[10:20,5]`, `nd[10:20,5:6]` zurück?

$\color{green}{\textbf{User 8}}$: 

### Neuro-Matrix

$\color{blue}{\text{Aufgabe 10}}$.	Stellen Sie sich vor, wir haben ein Neuronales Netz mit 2 Inputs $i_k$ und 3 Hidden Neuronen $h_j$. Dazwischen liegen Gewichte, die man am besten in einer Matrix $\mathbf{W}_{jk}$ darstellt. Schreiben Sie ein kleines Python-Programm, das mittels Matrixmultiplikation aus NumPy die Aktivierung der Hidden Neurone berechnet, wenn am Input 
$\,\,\mathbf{i} =
  \left(\begin{matrix} 1.5 \\ -0.3
  \end{matrix}\right)$
 anliegt und die Gewichtsmatrix lautet
$$\mathbf{W} = 
  \left(\begin{matrix} 1 & 0 \\
                       2 & 0.5 \\
                       -1& 3
  \end{matrix}\right)$$

Testen Sie verschiedene Python Data Types, verschiedene Python Operatoren bzw. Methoden. Was geht, was nicht?

---

### Replicator

$\color{blue}{\text{Aufgabe 11}}$. Sei $\mathbf{y}=\left(\begin{matrix} 1 & 2 & 4 \end{matrix}\right)$ ein Vektor. Wie können Sie mit *einem* Befehl daraus eine 5x3 Matrix 
$\left(\begin{matrix} 1 & 2 & 4 \\
                      & \cdots& \\
                      1 & 2 & 4\end{matrix}\right)$ erzeugen, die den Vektor $\mathbf{y}$ auf 5 Zeilen repliziert? Bzw. auf 7 Zeilen? Finden Sie mehrere solche Ein-Befehl-Lösungen.